url: "https://diegostesi-byte.github.io"
baseurl: "/El-Espejo-de-Fuego"
title: El Espejo del Fuego
description: Historias humanas, divulgación y conocimiento aplicado sobre incendios forestales.
lang: es
markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
